data_directory = '/var/lib/postgresql/data'
hba_file = '/etc/unciv-authoritative/postgres/pg_hba.conf'
ident_file = '/var/lib/postgresql/data/pg_ident.conf'

include = '/etc/unciv-authoritative/postgres/tls.conf'
include = '/etc/unciv-authoritative/postgres/pitr.conf'

io_method = worker
io_min_workers = 1
io_max_workers = 2
io_max_concurrency = 16
autovacuum_max_parallel_workers = 1
shared_buffers = '192MB'
max_connections = 64
log_connections = on
log_disconnections = on
log_min_duration_statement = '1s'
log_lock_waits = on
deadlock_timeout = '1s'
