listen_addresses = '127.0.0.1,::1'
password_encryption = 'scram-sha-256'
ssl = on
ssl_cert_file = '/etc/unciv-authoritative/postgres/tls/server.crt'
ssl_key_file = '/etc/unciv-authoritative/postgres/tls/server.key'
ssl_ca_file = '/etc/unciv-authoritative/postgres/tls/ca.crt'
ssl_min_protocol_version = 'TLSv1.2'
ssl_prefer_server_ciphers = on
