use super::*;

#[derive(OpenApi)]
#[openapi(
    paths(
        health,
        readiness,
        capabilities,
        openapi_document,
        asyncapi_document,
        register,
        login,
        refresh_session,
        logout,
        logout_all_sessions,
        recover_account,
        replace_recovery_codes,
        change_password,
        disable_account,
        delete_account,
        list_friends,
        request_friend,
        accept_friend,
        remove_friend_request,
        remove_friend,
        list_games,
        list_lobbies,
        lobby,
        reconfigure_lobby,
        select_lobby_faction,
        set_lobby_ready,
        start_lobby,
        list_game_chat,
        post_game_chat,
        list_ruleset_manifests,
        create_game,
        game_metadata,
        rewind_checkpoints,
        propose_rewind,
        current_rewind,
        rewind_status,
        vote_rewind,
        transfer_ownership,
        invite_player,
        list_player_invitations,
        close_game_admin,
        archive_game_admin,
        game_projection,
        game_projection_delta,
        websocket_notifications,
        add_spectator,
        leave_spectator,
        revoke_spectator,
        spectator_projection,
        join_game,
        end_turn,
        resign,
        force_resign,
        kick_member,
        move_unit,
        move_unit_toward,
        cancel_unit_movement_order,
        set_unit_exploration,
        set_unit_automation,
        set_unit_posture,
        disband_unit,
        pillage_tile,
        found_city,
        paradrop_unit,
        attack_with_unit,
        bombard_with_city,
        launch_nuclear_strike,
        air_sweep,
        upgrade_units,
        promote_unit,
        set_city_unit_promotion_preference,
        rename_unit,
        set_tile_improvement_order,
        set_road_connection_order,
        swap_units,
        queue_construction,
        queue_construction_at_tile,
        set_perpetual_construction,
        remove_construction,
        move_construction,
        manage_construction_queues,
        purchase_construction,
        purchase_construction_at_tile,
        buy_city_tile,
        buy_city_tile_batch,
        sell_building,
        set_city_governance,
        resolve_city_disposition,
        cast_diplomatic_vote,
        choose_great_person,
        use_great_person_unit,
        gift_unit,
        add_unit_to_capital_project,
        transform_unit,
        trigger_unit_unique,
        create_instant_improvement,
        use_religious_unit,
        choose_religious_beliefs,
        offer_trade,
        retract_trade_offer,
        accept_trade,
        decline_trade,
        counter_trade,
        declare_war,
        denounce_civilization,
        offer_friendship,
        make_diplomatic_demand,
        respond_to_diplomatic_prompt,
        respond_to_city_state_protection_prompt,
        gift_city_state_gold,
        set_city_state_protection,
        demand_city_state_tribute,
        gift_city_state_improvement,
        negotiate_city_state_peace,
        marry_city_state,
        move_spy,
        set_spy_coup,
        resolve_event_choice,
        set_city_tile_assignment,
        set_specialist_count,
        set_manual_specialists,
        reset_citizens,
        set_avoid_growth,
        set_citizen_focus,
        set_research_path,
        manage_research_queue,
        adopt_policy,
        choose_free_technology,
        acknowledge_research_completion
    ),
    components(schemas(
        HealthResponse,
        ReadinessResponse,
        CapabilitiesResponse,
        CredentialsRequest,
        AccountResponse,
        LoginResponse,
        SessionResponse,
        RecoverAccountRequest,
        RecoveryCodesResponse,
        ChangePasswordRequest,
        ConfirmPasswordRequest,
        FriendRequest,
        PostGameChatRequest,
        unciv_authoritative_server::postgres::FriendSummary,
        unciv_authoritative_server::postgres::FriendRequestSummary,
        unciv_authoritative_server::postgres::SocialGraph,
        unciv_authoritative_server::postgres::GameChatMessage,
        unciv_authoritative_server::postgres::GameChatPage,
        CreateGameRequest,
        CreateGameSetupRequest,
        unciv_authoritative_server::worker::GeneratedMapType,
        unciv_authoritative_server::worker::GeneratedMapShape,
        unciv_authoritative_server::worker::GeneratedMapSize,
        unciv_authoritative_server::worker::MapResourceDensity,
        unciv_authoritative_server::worker::BarbarianMode,
        unciv_authoritative_server::postgres::PublicRulesetIdentity,
        unciv_authoritative_server::postgres::RulesetManifestSummary,
        unciv_authoritative_server::postgres::RulesetManifestPage,
        GameMetadataResponse,
        ProposeRewindRequest,
        VoteRewindRequest,
        unciv_authoritative_server::postgres::RewindCheckpoint,
        unciv_authoritative_server::postgres::RewindStatus,
        TransferOwnershipRequest,
        InvitePlayerRequest,
        unciv_authoritative_server::postgres::PlayerInvitation,
        GameAdminOperationRequest,
        EndTurnRequest,
        ResignRequest,
        ForceResignRequest,
        KickMemberRequest,
        JoinGameRequest,
        AddSpectatorRequest,
        RevokeSpectatorRequest,
        MoveUnitRequest,
        MoveUnitTowardRequest,
        CancelUnitMovementOrderRequest,
        SetUnitExplorationRequest,
        SetUnitAutomationRequest,
        SetUnitPostureRequest,
        DisbandUnitRequest,
        PillageTileRequest,
        FoundCityRequest,
        ParadropUnitRequest,
        AttackWithUnitRequest,
        BombardWithCityRequest,
        LaunchNuclearStrikeRequest,
        AirSweepRequest,
        UpgradeUnitsRequest,
        PromoteUnitRequest,
        SetCityUnitPromotionPreferenceRequest,
        RenameUnitRequest,
        SetTileImprovementOrderRequest,
        SetRoadConnectionOrderRequest,
        unciv_authoritative_server::UnitPosture,
        SwapUnitsRequest,
        QueueConstructionRequest,
        QueueConstructionAtTileRequest,
        SetPerpetualConstructionRequest,
        RemoveConstructionRequest,
        MoveConstructionRequest,
        ManageConstructionQueuesRequest,
        unciv_authoritative_server::ConstructionQueueAction,
        PurchaseConstructionRequest,
        PurchaseConstructionAtTileRequest,
        BuyCityTileRequest,
        BuyCityTileBatchRequest,
        SellBuildingRequest,
        SetCityGovernanceRequest,
        ResolveCityDispositionRequest,
        CastDiplomaticVoteRequest,
        ChooseGreatPersonRequest,
        UseGreatPersonUnitRequest,
        GiftUnitRequest,
        AddUnitToCapitalProjectRequest,
        TransformUnitRequest,
        TriggerUnitUniqueRequest,
        CreateInstantImprovementRequest,
        unciv_authoritative_server::GreatPersonUnitAction,
        UseReligiousUnitRequest,
        ChooseReligiousBeliefsRequest,
        OfferTradeRequest,
        RetractTradeOfferRequest,
        TradeRequestDecisionRequest,
        CounterTradeRequest,
        DiplomacyPartnerRequest,
        DiplomaticDemandRequest,
        DiplomaticPromptResponseRequest,
        CityStateProtectionPromptResponseRequest,
        unciv_authoritative_server::projection::CityStateProtectionResponse,
        unciv_authoritative_server::projection::DiplomaticDemand,
        unciv_authoritative_server::projection::DiplomacyPromptType,
        unciv_authoritative_server::projection::ProjectedDiplomacyPartner,
        unciv_authoritative_server::projection::ProjectedDiplomacyPrompt,
        unciv_authoritative_server::projection::ProjectedCityStatePartner,
        CityStateGoldGiftRequest,
        CityStateProtectionRequest,
        CityStateTributeRequest,
        CityStateImprovementGiftRequest,
        CityStatePeaceRequest,
        CityStateMarriageRequest,
        MoveSpyRequest,
        SetSpyCoupRequest,
        ResolveEventChoiceRequest,
        unciv_authoritative_server::projection::ProjectedSpy,
        unciv_authoritative_server::projection::ProjectedSpyAction,
        unciv_authoritative_server::projection::ProjectedEventPrompt,
        unciv_authoritative_server::projection::ProjectedEventChoice,
        unciv_authoritative_server::projection::ProjectedCityStateImprovementGift,
        unciv_authoritative_server::ReligiousUnitAction,
        unciv_authoritative_server::ReligiousBeliefType,
        unciv_authoritative_server::CityGovernanceAction,
        unciv_authoritative_server::CityDispositionAction,
        SetCityTileAssignmentRequest,
        SetSpecialistCountRequest,
        SetManualSpecialistsRequest,
        ResetCitizensRequest,
        SetAvoidGrowthRequest,
        SetCitizenFocusRequest,
        unciv_authoritative_server::CityTileAssignment,
        SetResearchPathRequest,
        ManageResearchQueueRequest,
        unciv_authoritative_server::ResearchQueueAction,
        AdoptPolicyRequest,
        ChooseFreeTechnologyRequest,
        AcknowledgeResearchCompletionRequest,
        ErrorResponse,
        unciv_authoritative_server::CommandAccepted,
        unciv_authoritative_server::postgres::GameSummary,
        unciv_authoritative_server::postgres::GamePage,
        unciv_authoritative_server::postgres::GameProjection,
        unciv_authoritative_server::GameProjectionDelta,
        unciv_authoritative_server::ProjectionDeltaOperation,
        unciv_authoritative_server::notifications::RevisionNotification,
        unciv_authoritative_server::projection::PlayerProjection,
        unciv_authoritative_server::projection::ProjectedTradePartner,
        unciv_authoritative_server::projection::ProjectedTradeRequest,
        unciv_authoritative_server::projection::ProjectedTrade,
        unciv_authoritative_server::projection::ProjectedTradeOffer,
        unciv_authoritative_server::projection::ProjectedCity,
        unciv_authoritative_server::projection::ProjectedCityDisposition,
        unciv_authoritative_server::projection::ProjectedCityTile,
        unciv_authoritative_server::projection::ProjectedSpecialist,
        unciv_authoritative_server::projection::ProjectedUnitPromotionPreference,
        unciv_authoritative_server::projection::CitizenFocus,
        unciv_authoritative_server::projection::ProjectedUnit,
        unciv_authoritative_server::projection::ProjectedUnitUpgradeTarget,
        unciv_authoritative_server::projection::ProjectedImprovementOrderChoice,
        unciv_authoritative_server::projection::ProjectedTileVisibility
    )),
    modifiers(&SecurityAddon),
    tags((name = "authoritative-multiplayer-v3", description = "Server-authoritative Unciv multiplayer API v3"))
)]
pub(super) struct ApiDoc;

pub(super) struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .description(Some("Opaque revocable API-v3 session token"))
                        .build(),
                ),
            );
        }
    }
}

#[utoipa::path(get, path = "/healthz", responses((status = 200, body = HealthResponse)))]
pub(super) async fn health() -> Json<HealthResponse> {
    Json(HealthResponse {
        status: "ok",
        protocol_version: PROTOCOL_VERSION,
    })
}

#[utoipa::path(
    get,
    path = "/readyz",
    responses(
        (status = 200, body = ReadinessResponse),
        (status = 503, body = ReadinessResponse)
    )
)]
pub(super) async fn readiness(
    State(state): State<AppState>,
) -> (StatusCode, Json<ReadinessResponse>) {
    let (postgres, engine_worker) =
        tokio::join!(state.repository.readiness_check(), state.worker.handshake());
    let ready = postgres.is_ok() && engine_worker.is_ok();
    (
        if ready {
            StatusCode::OK
        } else {
            StatusCode::SERVICE_UNAVAILABLE
        },
        Json(ReadinessResponse {
            status: if ready { "ready" } else { "unready" },
            protocol_version: PROTOCOL_VERSION,
            postgres: if postgres.is_ok() { "ready" } else { "unready" },
            engine_worker: if engine_worker.is_ok() {
                "ready"
            } else {
                "unready"
            },
        }),
    )
}

#[utoipa::path(get, path = "/api/v3/capabilities", responses((status = 200, body = CapabilitiesResponse)))]
pub(super) async fn capabilities() -> Json<CapabilitiesResponse> {
    Json(CapabilitiesResponse {
        protocol_version: PROTOCOL_VERSION,
        projection_version: PROJECTION_VERSION,
        commands: vec![
            "join_game",
            "move_unit",
            "move_unit_toward",
            "cancel_unit_movement_order",
            "set_unit_exploration",
            "set_unit_automation",
            "set_unit_posture",
            "disband_unit",
            "pillage_tile",
            "found_city",
            "paradrop_unit",
            "attack_with_unit",
            "bombard_with_city",
            "launch_nuclear_strike",
            "air_sweep",
            "upgrade_units",
            "promote_unit",
            "set_city_unit_promotion_preference",
            "rename_unit",
            "set_tile_improvement_order",
            "set_road_connection_order",
            "swap_units",
            "queue_construction",
            "queue_construction_at_tile",
            "set_perpetual_construction",
            "remove_construction",
            "move_construction",
            "manage_construction_queues",
            "purchase_construction",
            "purchase_construction_at_tile",
            "buy_city_tile",
            "buy_city_tile_batch",
            "sell_building",
            "set_city_governance",
            "resolve_city_disposition",
            "cast_diplomatic_vote",
            "choose_great_person",
            "use_great_person_unit",
            "gift_unit",
            "add_unit_to_capital_project",
            "transform_unit",
            "trigger_unit_unique",
            "create_instant_improvement",
            "use_religious_unit",
            "choose_religious_beliefs",
            "offer_trade",
            "retract_trade_offer",
            "accept_trade",
            "decline_trade",
            "counter_trade",
            "declare_war",
            "denounce_civilization",
            "offer_friendship",
            "make_diplomatic_demand",
            "respond_to_diplomatic_prompt",
            "respond_to_city_state_protection_prompt",
            "gift_city_state_gold",
            "set_city_state_protection",
            "demand_city_state_tribute",
            "gift_city_state_improvement",
            "negotiate_city_state_peace",
            "marry_city_state",
            "move_spy",
            "set_spy_coup",
            "resolve_event_choice",
            "set_city_tile_assignment",
            "set_specialist_count",
            "set_manual_specialists",
            "reset_citizens",
            "set_avoid_growth",
            "set_citizen_focus",
            "set_research_path",
            "manage_research_queue",
            "adopt_policy",
            "choose_free_technology",
            "acknowledge_research_completion",
            "end_turn",
            "resign",
            "force_resign",
            "kick_member",
        ],
        whole_state_upload: false,
        websocket_notifications: true,
        projection_deltas: true,
    })
}

#[utoipa::path(
    get,
    path = "/api/v3/openapi.json",
    responses((status = 200, description = "Generated OpenAPI 3.1 contract", body = serde_json::Value))
)]
pub(super) async fn openapi_document() -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}
